### ISSUE TITLE
[OpenSSL] OpenSSL fails to build when cross-compiling Linux to Windows

### ISSUE THREAD

**Issue by allquixotic** [conan-community/community#29] opened 2018-07-09 13:18 UTC
### Description of Problem

OpenSSL fails to build from source when cross-compiling from Linux (Ubuntu 18.04 in this case) to Windows using the MinGW64 cross compilation toolchain.

### Build log from console
```
OpenSSL/1.0.2o@conan/stable: Building your package in /home/c9/.conan/data/OpenSSL/1.0.2o/conan/stable/build/34c14cb158f170a1ac11591fc08ddea87a9bfed0
OpenSSL/1.0.2o@conan/stable: Configuring sources in /home/c9/.conan/data/OpenSSL/1.0.2o/conan/stable/source
OpenSSL/1.0.2o@conan/stable: Downloading https://www.openssl.org/source/openssl-1.0.2o.tar.gz
[==================================================] 5.3MB/5.3MB
OpenSSL/1.0.2o@conan/stable: Copying sources to build folder
OpenSSL/1.0.2o@conan/stable: Generator txt created conanbuildinfo.txt
OpenSSL/1.0.2o@conan/stable: Calling build()
OpenSSL/1.0.2o@conan/stable:
OpenSSL/1.0.2o@conan/stable: ERROR: Package '34c14cb158f170a1ac11591fc08ddea87a9bfed0' build failed
OpenSSL/1.0.2o@conan/stable: WARN: Build folder /home/c9/.conan/data/OpenSSL/1.0.2o/conan/stable/build/34c14cb158f170a1ac11591fc08ddea87a9bfed0
ERROR: OpenSSL/1.0.2o@conan/stable: Error in build() method, line 90
        lib_path = "%s/%s.lib" % (zlib_info.lib_paths[0], zlib_info.libs[0])
        IndexError: list index out of range
```

**Note:** Since the build log specifies zlib, here's the build log from zlib immediately prior:

```
zlib/1.2.11@conan/stable: Package '040db29ed48cb6d2bb9f4c6d13e74d5e319c7ad8' built
zlib/1.2.11@conan/stable: Build folder /home/c9/.conan/data/zlib/1.2.11/conan/stable/build/040db29ed48cb6d2bb9f4c6d13e74d5e319c7ad8
zlib/1.2.11@conan/stable: Generated conaninfo.txt
zlib/1.2.11@conan/stable: Generated conanbuildinfo.txt
zlib/1.2.11@conan/stable: Generating the package
zlib/1.2.11@conan/stable: Package folder /home/c9/.conan/data/zlib/1.2.11/conan/stable/package/040db29ed48cb6d2bb9f4c6d13e74d5e319c7ad8
zlib/1.2.11@conan/stable: Calling package()
zlib/1.2.11@conan/stable: WARN: local cache: True
zlib/1.2.11@conan/stable: WARN: develop: False
zlib/1.2.11@conan/stable package(): Copied 1 file: LICENSE
zlib/1.2.11@conan/stable package(): Copied 1 '.pc' file: zlib.pc
zlib/1.2.11@conan/stable package(): Copied 13 '.h' files:
zlib/1.2.11@conan/stable: Package '040db29ed48cb6d2bb9f4c6d13e74d5e319c7ad8' created
```

### Conan profile used:
```
[env]
# Where is our C compiler
CC=/usr/bin/x86_64-w64-mingw32-gcc-7.3-win32
# Where is our CPP compiler
CXX=/usr/bin/x86_64-w64-mingw32-g++-win32

[settings]
# We are building in Ubuntu Linux
os_build=Linux
arch_build=x86_64

# We are cross building to Windows
os=Windows
arch=x86_64
compiler=gcc
# Adjust to the gcc version of your MinGW package
compiler.version=7.3
compiler.libcxx=libstdc++11
build_type=Release
```

### Package Details
* Package Name/Version: **OpenSSL/1.0.2o@conan/stable**
* Operating System: **Ubuntu 18.04 64-bit cross-compiling to Windows 64-bit**
* Compiler+version: 
```
$ x86_64-w64-mingw32-gcc-7.3-win32 -v
Using built-in specs.
COLLECT_GCC=x86_64-w64-mingw32-gcc-7.3-win32
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-w64-mingw32/7.3-win32/lto-wrapper
Target: x86_64-w64-mingw32
Configured with: ../../src/configure --build=x86_64-linux-gnu --prefix=/usr --includedir='/usr/include' --mandir='/usr/share/man' --infodir='/usr/share/info' --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir='/usr/lib/x86_64-linux-gnu' --libexecdir='/usr/lib/x86_64-linux-gnu' --disable-maintainer-mode --disable-dependency-tracking --prefix=/usr --enable-shared --enable-static --disable-multilib --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --libdir=/usr/lib --enable-libstdcxx-time=yes --with-tune=generic --with-headers=/usr/x86_64-w64-mingw32/include --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libgomp --enable-languages=c,c++,fortran,objc,obj-c++,ada --enable-lto --with-plugin-ld --enable-threads=win32 --program-suffix=-win32 --program-prefix=x86_64-w64-mingw32- --target=x86_64-w64-mingw32 --with-as=/usr/bin/x86_64-w64-mingw32-as --with-ld=/usr/bin/x86_64-w64-mingw32-ld --enable-libatomic --enable-libstdcxx-filesystem-ts=yes
Thread model: win32
gcc version 7.3-win32 20180312 (GCC)
$ aptitude show gcc-mingw-w64-x86-64
Package: gcc-mingw-w64-x86-64
Version: 7.3.0-11ubuntu1+20.2build1
State: installed
Automatically installed: yes
Priority: extra
Section: universe/devel
Maintainer: Stephen Kitt <skitt@debian.org>
Architecture: amd64
Uncompressed Size: 137 M
Depends: binutils-mingw-w64-x86-64, mingw-w64-x86-64-dev, gcc-mingw-w64-base (= 7.3.0-11ubuntu1+20.2build1), libc6 (>= 2.15), libgcc1
         (>= 1:4.2), libgmp10, libisl19 (>= 0.15), libmpc3, libmpfr6 (>= 3.1.3), libstdc++6 (>= 5.2), zlib1g (>= 1:1.1.4)
Suggests: gcc-7-locales (>= 7.3.0)
Conflicts: gcc-mingw-w64-bootstrap
Breaks: gcc-mingw-w64 (< 4.6.3-1ubuntu5+5ubuntu1)
Replaces: gcc-mingw-w64 (< 4.6.3-1ubuntu5+5ubuntu1), gcc-mingw-w64-bootstrap
Description: GNU C compiler for MinGW-w64 targeting Win64
 MinGW-w64 provides a development and runtime environment for 32- and 64-bit (x86 and x64) Windows applications using the Windows API
 and the GNU Compiler Collection (gcc).

 This package contains the C compiler, supporting cross-compiling to 64-bit MinGW-w64 targets.
Homepage: http://www.gnu.org/software/gcc/
```

**Comment by SSE4** [comment] 2018-07-09 13:57
seems like zlib library is not exported for some reason, that must be an issue

**Comment by lasote** [comment] 2018-07-11 11:04
Looks like the issue is with zlib. It is building unexpectedly some .so files even using the cross compiler and then it doesn't export anything in the "lib" package folder. So OpenSSL fails to use it.

**Comment by lasote** [comment] 2018-07-11 13:22
Here at https://github.com/conan-community/conan-zlib/pull/40 is a patch for zlib. I will merge it when the CI is ready.
The OpenSSL package also requires some adjustments, I will push it when zlib is ready.

**Comment by lasote** [comment] 2018-07-11 13:23
By the way, your profile is not complete enough and probably the zlib building will fail. Use this:

```
standalone_toolchain=/usr/x86_64-w64-mingw32 # Adjust this path
target_host=x86_64-w64-mingw32
cc_compiler=gcc
cxx_compiler=g++

[env]
CONAN_CMAKE_FIND_ROOT_PATH=$standalone_toolchain
CHOST=$target_host
AR=$target_host-ar
AS=$target_host-as
RANLIB=$target_host-ranlib
CC=$target_host-$cc_compiler
CXX=$target_host-$cxx_compiler
STRIP=$target_host-strip
RC=$target_host-windres

[settings]
# We are building in Ubuntu Linux
os_build=Linux
arch_build=x86_64

# We are cross building to Windows
os=Windows
arch=x86_64
compiler=gcc

# Adjust to the gcc version of your MinGW package
compiler.version=7.3
compiler.libcxx=libstdc++11
build_type=Release
```

**Comment by lasote** [comment] 2018-07-11 13:32
Docs updated:
https://docs.conan.io/en/latest/systems_cross_building/cross_building.html#linux-to-windows

**Comment by lasote** [comment] 2018-07-12 09:32
I've pushed the zlib package. (the recipe will be available in some minutes). Use "conan install/create --update" to get the latest version.
The openssl needs to be updated too.

**Comment by SSE4** [comment] 2018-07-15 17:35
last update from @allquixotic 
```
Cross-build from 'Linux:x86_64' to 'Windows:x86_64'
boost_build/1.66.0@bincrafters/stable: Already installed!
boost_package_tools/1.66.0@bincrafters/stable: Already installed!
bzip2/1.0.6@conan/stable: Already installed!
cmake_findboost_modular/1.66.0@bincrafters/stable: Already installed!
lzma/5.2.3@bincrafters/stable: Already installed!
sqlite3/3.21.0@bincrafters/stable: Already installed!
zlib/1.2.11@conan/stable: Already installed!
OpenSSL/1.0.2o@conan/stable: Building your package in /home/c9/.conan/data/OpenSSL/1.0.2o/conan/stable/build/34c14cb158f170a1ac11591fc08ddea87a9bfed0
OpenSSL/1.0.2o@conan/stable: Copying sources to build folder
OpenSSL/1.0.2o@conan/stable: Generator txt created conanbuildinfo.txt
OpenSSL/1.0.2o@conan/stable: Calling build()
OpenSSL/1.0.2o@conan/stable: =====> Options:  --with-zlib-include="/home/c9/.conan/data/zlib/1.2.11/conan/stable/package/040db29ed48cb6d2bb9f4c6d13e74d5e319c7ad8/include" --with-zlib-lib="/home/c9/.conan/data/zlib/1.2.11/conan/stable/package/040db29ed48cb6d2bb9f4c6d13e74d5e319c7ad8/lib/z.lib"
OpenSSL/1.0.2o@conan/stable: WARN: ./Configure mingw64  --with-zlib-include="/home/c9/.conan/data/zlib/1.2.11/conan/stable/package/040db29ed48cb6d2bb9f4c6d13e74d5e319c7ad8/include" --with-zlib-lib="/home/c9/.conan/data/zlib/1.2.11/conan/stable/package/040db29ed48cb6d2bb9f4c6d13e74d5e319c7ad8/lib/z.lib"
OpenSSL/1.0.2o@conan/stable:
OpenSSL/1.0.2o@conan/stable: ERROR: Package '34c14cb158f170a1ac11591fc08ddea87a9bfed0' build failed
OpenSSL/1.0.2o@conan/stable: WARN: Build folder /home/c9/.conan/data/OpenSSL/1.0.2o/conan/stable/build/34c14cb158f170a1ac11591fc08ddea87a9bfed0
ERROR: OpenSSL/1.0.2o@conan/stable: Error in build() method, line 119
        self.mingw_build(config_options_string)
while calling 'mingw_build', line 350
        tools.run_in_windows_bash(self, config_line)
        ConanException: Command only for Windows operating system
```

**Comment by SSE4** [comment] 2018-11-27 13:12
@allquixotic this appears to be already fixed in (https://github.com/conan-community/conan-openssl/commit/5fcf4e1f3aa7755809b1cd951ef087283aed1c8c). I've tried to run on docker (https://hub.docker.com/r/bincrafters/docker-mingw-gcc7/) and it worked for me. could you possibly give an another try?

**Comment by SSE4** [comment] 2019-01-30 14:43
@allquixotic I am closing this one for now, as required changes were applied. please open new issue, if you still have a problem.

**Closed by SSE4** 2019-01-30 14:43 UTC
Labels: Feedback please!, complex: low, fixed, priority: medium, type: bug
