### ISSUE TITLE
[boost] builds are stored unversioned and on C:\ instead of %USERPROFILE% with Visual Studio

### ISSUE THREAD

**Issue by firewave** [conan-community/community#133] opened 2019-01-10 14:34 UTC
### Description of Problem, Request, or Question

When building boost with Visual Studio 2015 (I have no other version available) it uses `C:\.conan` instead of `%USERPROFILE%\.conan\data\boost\1.69\local\testing\package` (`local/testing` is my custom source). This does not appear to be a recent issue (I started using the recipe with 1.67).

I have several other libraries which use the proper `%USERPROFILE%` location.

### Package Details
* Package Name/Version: **boost/1.69**
* Operating System: **Windows 10**
* Operation System Version: **Version 1809 (OS Build 17763.253)**
* Compiler+version: **MSVC 19.0.24215.1**
* Conan version: **conan 1.11.1**
* Python version: **python 3.6.4**

### Build logs
```
boost/1.69.0@local/testing: Building your package in C:\.conan\9ijg2zvn\1
boost/1.69.0@local/testing: Configuring sources in C:/.conan\y9qffx83\1
...
boost/1.69.0@local/testing: Package 'a8f1b413ade253d7f8c1618055f6f61b45de30f9' built
boost/1.69.0@local/testing: Build folder C:\.conan\9ijg2zvn\1
boost/1.69.0@local/testing: Generated conaninfo.txt
boost/1.69.0@local/testing: Generated conanbuildinfo.txt
boost/1.69.0@local/testing: Generating the package
boost/1.69.0@local/testing: Package folder C:/.conan\ddrdjxxp\1
...
boost/1.69.0@local/testing: WARN: No files copied from build folder!
```

**Comment by danimtb** [comment] 2019-01-10 16:03
hi @firewave,

This is intended behavior in Conan due to limitation in paths on Windows. Recipes can activate `short_paths` to perform source, build, package... steps in a shorter path folder: https://docs.conan.io/en/latest/reference/conanfile/attributes.html#short-paths

It is activated in the boost recipe here: https://github.com/conan-community/conan-boost/blob/release/1.69.0/conanfile.py#L47

You can disable this behavior globally using environment variables here: https://docs.conan.io/en/latest/reference/env_vars.html#conan-user-home-short

Hope it helps 😄

**Comment by SSE4** [comment] 2019-01-30 14:47
@firewave do you have your question answered?

**Comment by danimtb** [comment] 2019-01-31 15:42
Closing this as it is the intended behavior and question was answered. Please feel free to comment any further issue. Thanks!

**Closed by danimtb** 2019-01-31 15:42 UTC
Labels: Feedback please!, type: question

**Comment by firewave** [comment] 2019-02-14 08:44
Thanks for the explanation!

I find the behavior more than horrifying though...

**Comment by danimtb** [comment] 2019-02-14 22:19
yeah, we too. But this is type of nasty tricks you have to do everytime on windows to get it working.

We recently introduced a configuration variable that can be set to None globally to disable dis behavior in all recipes. You have to set ``use_always_short_paths = None`` in you configuration file *~/.conan/conan.conf*. There is also an env var that will make the same effect: ``CONAN_USE_ALWAYS_SHORT_PATHS`` https://docs.conan.io/en/latest/reference/env_vars.html#conan-use-always-short-paths

Hope you find them useful 😄
