### ISSUE TITLE
[Boost] Boost 1.69.0 build error with zlib

### ISSUE THREAD

**Issue by rea-yseop** [conan-community/community#150] opened 2019-02-18 14:13 UTC
### Description of Problem, Request, or Question
Since the last update, when trying to install boost via conan, I have the following error:

```
ERROR: boost/1.69.0@conan/stable: Error in build() method, line 393
        flags = self.get_build_flags()
while calling 'get_build_flags', line 507
        add_defines(self.options.zlib, "zlib")
while calling 'add_defines', line 504
        for define in self.deps_cpp_info[library].defines:
        KeyError: 'zlib'
```

### Package Details (Include if Applicable)
* Package Name/Version: **boost/1.69.0**
* Operating System: **Linux**
* Compiler+version: **gcc-8**

### Steps to reproduce (Include if Applicable)

profile_linux
```
[settings]
os=Linux
arch=x86_64
compiler=gcc
compiler.version=8
compiler.libcxx=libstdc++11
build_type=Release

[build_requires]
boost/1.69.0@conan/stable
```

run `conan install boost/1.69.0@conan/stable --profile profile_linux`

**Comment by SSE4** [comment] 2019-02-19 05:54
@rea-yseop weird, I was unable to reproduce via your profile. also, why do you use boost in `build_requires`?
I see one case when it may potentially fail, applied a fix: https://github.com/conan-community/conan-boost/commit/787b7d526ff94f613f0d0b6706eb934daa044959
please give an another try.

**Comment by rea-yseop** [comment] 2019-02-19 08:06
Hello, I'm still new to conan so the boost in `build_requires` was maybe not necessary. 
I retried and your fix is working, thank you.

**Comment by SSE4** [comment] 2019-02-19 08:09
confirmed as fixed, closing

**Closed** 2019-02-19 08:09 UTC
Labels: Feedback please!, fixed
