### ISSUE TITLE
[Curl] broken on Windows with clang-cl

### ISSUE THREAD

**Issue by acgetchell** [conan-community/community#222] opened 2019-06-11 02:55 UTC
### Package Details (Include if Applicable)
* Package Name/Version: **libcurl/7.56.1**
* Operating System: **Windows**
* Compiler+version: **clang-cl**
* Conan version: **conan 1.16.0**
* Python version: **python 2.7.0**

### Steps to reproduce (Include if Applicable)

On AppVeyor with:

https://github.com/acgetchell/CDT-plusplus/blob/develop/.appveyor.yml
https://github.com/acgetchell/CDT-plusplus/blob/develop/CMakeLists.txt

### Build logs (Include if Available)

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/07v9b44r8uhc99o3?fullLog=true#L23099

**Comment by SSE4** [comment] 2019-06-11 10:36
I think in case of `clang-cl` CMake build should be used as well
I suppose we should change condition here:
https://github.com/bincrafters/conan-libcurl/blob/testing/7.64.1/conanfile.py#L138

**Comment by SSE4** [comment] 2019-06-18 19:28
@acgetchell I've applied required changes: https://github.com/bincrafters/conan-libcurl/commit/b2c5e1ec55c96c45ded6849101fec82329d114c7
please give an another try and lemme know

**Comment by acgetchell** [comment] 2019-06-22 18:36
Still failing:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/2qdp2y5dlnp0kpr4#L23411

**Comment by SSE4** [comment] 2019-06-24 09:38
for the record, the problem is with zlib:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZLIB_LIB_zlib
```

**Comment by SSE4** [comment] 2019-08-30 08:52
@acgetchell we have deleted our own `FindZLIB.cmake`: https://github.com/conan-community/conan-zlib/commit/1309a905d72e61c2ba261728e7614b44268560e0
could you possibly give an another try?

**Comment by acgetchell** [comment] 2019-08-30 21:38
Okay, `zlib` seems to build, but the Curl package still doesn't build because `OpenSSL` doesn't build:

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/95hfc04l0ho3s91f#L4804

**Comment by SSE4** [comment] 2019-08-30 21:57
glad to here, I'll make a fix for OpenSSL and let you know

**Comment by SSE4** [comment] 2019-09-04 13:54
@acgetchell I've applied some fixes:
zlib: https://github.com/conan-community/conan-zlib/commit/dc3bfc1b2ec970808a42a155f5c7f77eabd6221c
openssl: https://github.com/conan-community/conan-openssl/commit/037b959f11a34f513573efc5ec0368b1ba175734
with changes listed above I was able to build `libcurl/7.56.1` locally with the following conan profile:
```
include(default)
[settings]
compiler=clang
compiler.version=8
compiler.libcxx=libstdc++
[options]
[env]
CC=clang-cl  -mrtm
CXX=clang-cl  -mrtm
CFLAGS= -fms-compatibility-version=1800
CXXFLAGS= -fms-compatibility-version=1800
CONAN_CMAKE_GENERATOR=Ninja
PATH=[C:\Program Files\LLVM\bin]
[build_requires]
ninja_installer/1.8.2@bincrafters/stable
```

**Comment by SSE4** [comment] 2019-09-25 12:49
I am closing this one as changes were applied

**Closed by SSE4** 2019-09-25 12:49 UTC
Labels: Feedback please!, fixed

**Comment by acgetchell** [comment] 2019-10-11 02:44
Yes, I can confirm curl builds on Windows. Thank you!

https://ci.appveyor.com/project/acgetchell/cdt-plusplus/build/job/pauvvbq40u3e510i#L24811

**Comment by DrunkenMastah** [comment] 2020-10-22 06:06
I was facing the exact same problem with mingw on windows so I got some inspirations from SSE4 profile .
Here is the solution for anyone encountering it:

```
include(default)
[env]
CC=gcc  -mrtm
CXX=g++  -mrtm
CFLAGS= -fms-extensions
CXXFLAGS= -fms-extensions
CONAN_CMAKE_GENERATOR=Ninja
PATH=[C:\mingw810_64\bin]
[build_requires]
ninja_installer/1.8.2@bincrafters/stable
```
